LukeMathWalker/pavex

- ARCHITECTURE.md
PlantUML is not natively rendered by GitHub, while `mermaid` seems to be supported out of the box. That makes it easier for people to browser without having to install or learn how to use new software.
> Move from PlantUML to mermaid

- libs/pavex/src/language/resolved_path.rs
- libs/pavex/src/rustdoc.rs
- libs/pavex/src/web/app.rs
- libs/pavex/src/web/diagnostic.rs
- libs/pavex_cli/tests/ui_tests/constructors_cannot_return_the_unit_type/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/constructors_cannot_return_the_unit_type/lib.rs
- libs/pavex_cli/tests/ui_tests/constructors_cannot_return_the_unit_type/test_config.toml
- libs/pavex_cli/tests/ui_tests/generic_handlers_are_not_supported/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/local_callable_paths_must_be_prefixed_with_crate/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/non_static_methods_are_not_supported/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/output_parameter_cannot_be_handled/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/output_parameter_cannot_be_handled/lib.rs
- libs/pavex_cli/tests/ui_tests/output_parameter_cannot_be_handled/test_config.toml
- libs/pavex_cli/tests/ui_tests/remote_callable_paths_must_be_absolute/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/structs_cannot_be_registered_as_handlers/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/structs_cannot_be_registered_as_handlers/lib.rs
- libs/pavex_cli/tests/ui_tests/structs_cannot_be_registered_as_handlers/test_config.toml
- libs/pavex_cli/tests/ui_tests/the_path_for_generic_arguments_must_be_absolute/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/tuple_input_parameters_are_not_handled/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/tuple_input_parameters_are_not_handled_by_constructors/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/tuple_input_parameters_are_not_handled_by_constructors/lib.rs
- libs/pavex_cli/tests/ui_tests/tuple_input_parameters_are_not_handled_by_constructors/test_config.toml
- libs/pavex_test_runner/src/main.rs
Provide useful diagnostics when failing to resolve the information for a callable registered as a constructor.
We make sure to reuse the logic we built for handlers while tuning the error messages.
> Process constructors errors

- examples/generated_app/src/lib.rs
- libs/pavex/src/web/app.rs
- libs/pavex/src/web/resolvers.rs
- libs/pavex/src/web/traits.rs
- libs/pavex_cli/tests/ui_tests/output_type_must_implement_into_response/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/output_type_must_implement_into_response/lib.rs
- libs/pavex_cli/tests/ui_tests/output_type_must_implement_into_response/test_config.toml
`pavex` would previously panic if the return type of error handlers/request handlers did not implement `IntoResponse`.
We now handle this case gracefully and return an appropriate error + suggestion.
Implementation hurdles: we had to add reverse maps for both request and error handlers In order to retrieve the callable identifiers starting from a callable object.
This whole "reverse walking" should probably be generalised, since we'll need it for every single diagnostic.
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> Verify that the output type of error handlers and request handlers implements `IntoResponse`

- libs/pavex/src/diagnostic/compiler_diagnostic.rs
- libs/pavex/src/diagnostic/mod.rs
- libs/pavex/src/web/analyses/computations.rs
- libs/pavex/src/web/analyses/constructibles.rs
- libs/pavex/src/web/analyses/router_validation.rs
Now it is aligned with how we expect related errors to be used: as additional annotated code snippets, not full-blown diagnostics.
This completes the miette-related work done in #17, at least for the time being.
> Rework the interface of CompilerDiagnostic

- libs/pavex/src/web/analyses/components.rs
- libs/pavex_cli/tests/ui_tests/constructors_input_parameters_cannot_be_generic/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/constructors_input_parameters_cannot_be_generic/lib.rs
We also add a label under the output type.
> Test the error message when there are multiple underconstrained generic parameters

- libs/pavex/src/compiler/route_parameter_validation.rs
- libs/pavex_cli/tests/ui_tests/route_parameters_happy_path/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/route_parameters_happy_path/expectations/diagnostics.dot
- libs/pavex_cli/tests/ui_tests/route_parameters_happy_path/lib.rs
- libs/pavex_cli/tests/ui_tests/route_parameters_happy_path/test.rs
- libs/pavex_cli/tests/ui_tests/route_parameters_non_existing_fields/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/route_parameters_unsupported_types/expectations/stderr.txt
Add support for catch-all parameters.
We also update test expectations and fix a compiler error that slipped through in #33.
> Catch-all route parameters

- libs/pavex/src/compiler/analyses/call_graph/application_state.rs
- libs/pavex/src/compiler/analyses/constructibles.rs
- libs/pavex/src/compiler/analyses/user_components/raw_db.rs
- libs/pavex/src/compiler/analyses/user_components/scope_graph.rs
- libs/pavex/src/compiler/codegen.rs
- libs/pavex/src/diagnostic/compiler_diagnostic.rs
- libs/pavex/src/diagnostic/mod.rs
- libs/pavex/src/diagnostic/registration_locations.rs
- libs/pavex_builder/src/blueprint.rs
- libs/pavex_builder/src/internals.rs
- libs/pavex_cli/tests/ui_tests/application_state_should_include_runtime_singletons_from_all_scopes/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/application_state_should_include_runtime_singletons_from_all_scopes/expectations/diagnostics.dot
- libs/pavex_cli/tests/ui_tests/nesting_fails_if_the_same_singleton_constructor_is_registered_in_different_scopes/expectations/stderr.txt
- libs/pavex_miette/src/graphical_report_handler.rs
Show a code snippet, in the help section, pointing at the blueprint you should register your constructor against if you want to share a singleton across all found instances.
Drive-by changes:
- Fix a few sources of non-determinism for the application state. The new test for scoping triggered these edge cases since the state constructor has more than one parameter.
> Improve diagnostic for ambiguous singletons

- libs/pavex/src/compiler/analyses/call_graph/borrow_checker/assign_order.rs
- libs/pavex/src/compiler/analyses/call_graph/borrow_checker/multiple_consumers.rs
- libs/pavex_cli/tests/ui_tests/borrow_checker/a_clonable_type_can_be_moved_twice/expectations/diagnostics.dot
- libs/pavex_cli/tests/ui_tests/borrow_checker/a_non_clonable_type_cannot_be_moved_twice/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/borrow_checker/multiple_consumers_pass_takes_control_flow_into_account_for_errors/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/borrow_checker/multiple_consumers_pass_takes_control_flow_into_account_for_errors/lib.rs
- libs/pavex_cli/tests/ui_tests/borrow_checker/multiple_consumers_pass_takes_control_flow_into_account_for_errors/test_config.toml
- libs/pavex_cli/tests/ui_tests/borrow_checker/you_can_consume_a_non_cloneable_type_from_two_different_control_flow_branches/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/borrow_checker/you_can_consume_a_non_cloneable_type_from_two_different_control_flow_branches/expectations/diagnostics.dot
- libs/pavex_cli/tests/ui_tests/borrow_checker/you_can_consume_a_non_cloneable_type_from_two_different_control_flow_branches/test_config.toml
Enhance the borrow checking passes to take into account control flow—if a type is consumed by two dependents, are those two dependents ever going to be executed one after the other?
E.g. one of those dependents is called in the `Ok` branch of a `match` statement, while the other is triggered on the `Err` branch. All good!
Control-flow awareness extends to our error reporting as well—when there is a conflict, we take care to only report the set of consumers that are actually competing to consume a certain type within the same control flow execution path.
> Borrow checking—Part 2

- libs/pavex/src/compiler/analyses/call_graph/application_state.rs
- libs/pavex/src/compiler/analyses/call_graph/borrow_checker/complex.rs
- libs/pavex/src/compiler/analyses/call_graph/borrow_checker/diagnostic_helpers.rs
- libs/pavex/src/compiler/analyses/call_graph/borrow_checker/multiple_consumers.rs
- libs/pavex/src/compiler/analyses/call_graph/core_graph.rs
- libs/pavex/src/compiler/analyses/call_graph/dependency_graph.rs
- libs/pavex/src/compiler/analyses/call_graph/mod.rs
- libs/pavex/src/compiler/analyses/call_graph/request_handler.rs
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/cycle_across_a_match_statement/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/cycle_across_a_match_statement/lib.rs
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/cycle_across_a_match_statement/test_config.toml
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/request_scoped_cycles/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/request_scoped_cycles/lib.rs
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/request_scoped_cycles/test_config.toml
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/transient_cycles/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/transient_cycles/lib.rs
- libs/pavex_cli/tests/ui_tests/dependency_injection/cycles/transient_cycles/test_config.toml
If a call graph contained a cycle, `pavex` would hang—either at a "constant" memory consumption (if the cycle was due to request scoped components) or spiraling out of control (if the cycle was due to transient components).
This PR introduces a new data structure, a `DependencyGraph`, whose primary purpose is ensuring that there are no cyclic dependencies _before_ trying to build a `CallGraph`.
In a `DependencyGraph` there is at most one node for each component, therefore we are guaranteed to halt. In a nutshell, a `DependencyGraph` is a slimmed down version of a `CallGraph` that disregards a bunch of information, in particular lifecycles.
There is some duplication of logic at the moment between `DependencyGraph` and `CallGraph`—we'll address it in a later PR.
> Emit an error for cyclic dependencies

- examples/realworld/.gitignore
- examples/realworld/Cargo.lock
- examples/realworld/app/Cargo.toml
- examples/realworld/app/src/bin/app.rs
- examples/realworld/app/src/configuration.rs
- examples/realworld/app/src/lib.rs
We deviate slightly from the [twelve-factor app](https://12factor.net/config) recommendations when it comes to configuration management.
We use a mix of configuration files and environment variables.
The configuration files that are checked into the repository are used for non-sensitive configuration values, while env variables can be used to override the default on a per-environment basis and to store sensitive values.
Config management is very sensitive to the infrastructural choices made _around_ the application (e.g. you might be injecting config files at startup time, or fetching values from something like Vault), therefore we don't "prescribe" what it needs to look like.
We use `figment` instead of `config` since it provides better error messages, although it's not what I'd consider …
> [Realworld example] Hierarchical configuration 

- examples/realworld/conduit_core/src/lib.rs
- libs/pavex/src/compiler/analyses/user_components/processed_db.rs
- libs/pavex/src/language/mod.rs
- libs/pavex/src/language/resolved_type.rs
- libs/pavex/src/rustdoc/compute/cache.rs
- libs/pavex/src/rustdoc/compute/mod.rs
- libs/pavex/src/rustdoc/queries.rs
It turns out that we were indexing all public paths and _some_ private paths for each items, since the `paths` field in `rustdoc`'s JSON output does contain some private paths if `--document-private-items` is passed to `cargo rustdoc`.
If we were to index only public paths, the error message that would get returned to the user is somewhat underwhelming: "we were not able to find X in crate Y, make sure it exists and it's public!".
`rustc`'s error message is instead more precise and actionable in this case: "X exists, but it's private because of Z".
Therefore we now index both public and private paths for each items.
I've also started to include hidden items in the docs, which is something I thought I did a while ago... but apparently not.
> Index both public and private paths.

- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/compiler/generated_app.rs
`cargo` takes into account the timestamp of the last modification when computing the fingerprint for a file (i.e. [its `mtime`](https://www.computerhope.com/jargon/m/mtime.htm)).
As a result, every time we touch a file, `cargo` marks it as dirty and triggers a rebuild.
This happens even if the file contents haven't changed, which is obviously undesirable.
This PR changes `pavex` behaviour to only write to disk if the file contents have actually changed.
It brings `cargo px check` on our Realworld example from 1.270s to 1.118s, an easy 150ms win!
> Avoid touching the filesystem if the file contents haven't changed

- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/compiler/analyses/user_components/processed_db.rs
- libs/pavex/src/compiler/app.rs
- libs/pavex/src/rustdoc/compute/cache.rs
- libs/pavex/src/rustdoc/compute/mod.rs
- libs/pavex/src/rustdoc/mod.rs
- libs/pavex/src/rustdoc/queries.rs
- libs/pavex_cli/src/main.rs
Our biggest bottleneck is computing JSON docs, so this is once again an optimisation to try to maximise how much work we are doing in parallel every time we invoke `rustdoc` or retrieve items from the cache.
It's difficult to determine which crate docs we need ahead of performing the actual analysis, which in turn leads to multiple invocations that are not fully utilising the cores available on the host machine.  
We can't do much to improve on this problem when executing for the first time, but we can do much better when optimising for the feedback loop of an interactive coding session. 
Every time `pavex_cli` is invoked for a project, we keep track of which crate docs are accessed and store it in SQLite at the end of the invocation.
We then retrieve this list when invoked again on the …
> Memoise needed crates across runs

- examples/realworld/Cargo.lock
- examples/realworld/api_server_sdk/blueprint.ron
- examples/realworld/api_server_sdk/src/lib.rs
- examples/realworld/conduit_core/src/articles/mod.rs
- examples/realworld/conduit_core/src/lib.rs
- libs/Cargo.lock
- libs/pavex/src/compiler/analyses/constructibles.rs
- libs/pavex/src/compiler/traits.rs
- libs/pavex_runtime/Cargo.toml
- libs/pavex_runtime/src/body/mod.rs
- libs/pavex_runtime/src/extract/body/buffered_body.rs
- libs/pavex_runtime/src/extract/body/errors.rs
- libs/pavex_runtime/src/extract/body/json.rs
- libs/pavex_runtime/src/extract/body/limit.rs
- libs/pavex_runtime/src/extract/body/mod.rs
- libs/pavex_runtime/src/extract/mod.rs
- libs/pavex_runtime/src/extract/query/query_params.rs
- libs/pavex_runtime/src/extract/route/raw_route_params.rs
- libs/pavex_runtime/src/extract/route/route_params.rs
In order to cover the remaining `/articles` routes in the Realworld spec, Pavex needs to be able to handle request bodies.
This PR adds:
- `BufferedBody`, an extractor that buffer the whole body of the incoming request in memory;
- `Json`, an extractor to deserialize a buffered body as JSON;
- `BodySizeLimits`, a configuration knob for `BufferedBody` that determines if there is a limit on the size of the body of incoming requests.
We ran into a few unrelated issues though:
- In order to override the limit on a per-request basis, the compiler must allow for constructors whose inputs are in a _child_ scope. At the moment, we require them to be in either the same scope or a parent scope;
- In order to server `POST /articlees` from a nested blueprint with an `/articles` prefix, we must allow …
> Add Json, BufferedBody and BodySizeLimits

- libs/Cargo.lock
- libs/pavex_runtime/Cargo.toml
- libs/pavex_runtime/src/extract/body/buffered_body.rs
- libs/pavex_runtime/src/extract/body/errors.rs
- libs/pavex_runtime/src/extract/body/json.rs
Using `serde_path_to_error` will give us better error messages.
I've added a snapshot test to check the error out, as well as fixing a broken doc test that slipped through the cracks.
> Improve deserialization errors for the JsonBody extractor.

- CONTRIBUTING.md
- examples/realworld/Cargo.lock
- examples/skeleton/Cargo.lock
- libs/Cargo.lock
- libs/Cargo.toml
- libs/pavex_cli/tests/ui_tests/blueprint/nesting/nest_at_prefix_is_validated/expectations/stderr.txt
- libs/pavex_test_runner/Cargo.toml
- libs/pavex_test_runner/src/lib.rs
- libs/pavex_test_runner/src/target_directory.rs
Each UI test is its own `cargo` project with its own target directory.
This has now become a problem since there are ~70 UI tests and my laptop is running out of space.
We introduce a pool of target directories and assign them dynamically to each test case when they are run. This ensures that we have an upper limit on the disk usage without compromising on test parallelism.
> Use a pool of target directories for UI tests

- examples/realworld/Cargo.toml
- examples/skeleton/Cargo.toml
- examples/skeleton/app_server_sdk/src/lib.rs
- libs/pavex/src/compiler/analyses/user_components/raw_db.rs
- libs/pavex_builder/src/blueprint.rs
- libs/pavex_cli/tests/ui_tests/blueprint/nesting/nest_at_prefix_is_validated/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/nesting/nest_at_prefix_is_validated/lib.rs
- libs/pavex_cli/tests/ui_tests/blueprint/router/route_path_is_validated/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/router/route_path_is_validated/lib.rs
This PR tweaks the constraints on path and path prefixes:
- It now allows empty paths, which is required in order to serve the base URL (without a trailing slash). It also unblocks serving `GET /articles` from the a nested blueprint with prefix `/articles` in the Realworld example;
- We add a new restriction on path prefixes, enforcing that they don't end with a trailing slash. This ensures that consecutive slashes in paths are (mostly) intentional.
> Fix path rules.

- examples/realworld/Cargo.lock
- examples/realworld/api_server_sdk/blueprint.ron
- examples/realworld/api_server_sdk/src/lib.rs
- examples/realworld/conduit_core/Cargo.toml
- examples/realworld/conduit_core/src/api/articles/delete_article.rs
- examples/realworld/conduit_core/src/api/articles/delete_comment.rs
- examples/realworld/conduit_core/src/api/articles/favorite_article.rs
- examples/realworld/conduit_core/src/api/articles/get_article.rs
- examples/realworld/conduit_core/src/api/articles/list_comments.rs
- examples/realworld/conduit_core/src/api/articles/publish_comment.rs
- examples/realworld/conduit_core/src/api/articles/unfavorite_article.rs
- examples/realworld/conduit_core/src/api/articles/update_article.rs
- examples/realworld/conduit_core/src/api/mod.rs
- examples/realworld/conduit_core/src/api/profiles/follow_user.rs
- examples/realworld/conduit_core/src/api/profiles/get_user.rs
- examples/realworld/conduit_core/src/api/profiles/mod.rs
- examples/realworld/conduit_core/src/api/profiles/unfollow_user.rs
- examples/realworld/conduit_core/src/api/tags.rs
- examples/realworld/conduit_core/src/api/users/get_user.rs
- examples/realworld/conduit_core/src/api/users/login.rs
- examples/realworld/conduit_core/src/api/users/mod.rs
- examples/realworld/conduit_core/src/api/users/signup.rs
- examples/realworld/conduit_core/src/api/users/update_user.rs
- libs/pavex_macros/src/lib.rs
This completes the modelling push for the request-side of the Realworld spec.
Miscellaneous:
- Fixed an issue in the `RouteParams` macro that would result in compiler errors if other derive macros were added _after_ `#[RouteParams]`.
- Use `#[RouteParams]` instead of `serde::Deserialize` when working with route parameters.
> Missing routes for Realworld

- examples/realworld/api_server_sdk/src/lib.rs
- libs/pavex_cli/tests/ui_tests/app_builder/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/blueprint/common/constructors_and_handlers_can_fail/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/blueprint/constructors/output_type_of_constructors_can_contain_generic_parameters/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/borrow_checker/control_flow/you_can_consume_a_non_cloneable_type_from_two_different_control_flow_branches/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/route_parameters/route_parameters_happy_path/expectations/app.rs
- libs/pavexc/src/compiler/analyses/call_graph/codegen.rs
All `Err` branches in our `match` expressions lead to an early return.
By actually making the `return` explicit, we can limit the visual drift to the right in the generated code, improving its readability.
> Reduce nesting in generated code

- libs/pavex/src/blueprint/reflection/callable/mod.rs
The new nightly build of IntellijRust fixes the IDE issues we were experiencing in the `f!` macro.
In order to get go-to-definition working as expected, they have suggested to use `const` as IDE hint rather than `let`. This seems to work in both IntellijRust and rust-analyzer, so I applied the change in this PR.
> Fix completion suggestions and go-to-definition in f! for IntellijRust

- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/blueprint/blueprint.rs
- libs/pavex/src/blueprint/internals.rs
- libs/pavex/src/blueprint/mod.rs
- libs/pavex/src/blueprint/reflection/mod.rs
- libs/pavex/src/lib.rs
- libs/pavex/src/middleware.rs
Going for a slightly different approach on wrapping middleware: multiple small PRs rather than getting the whole thing done at once.
This is the first step: defining the API exposed via `Blueprint` and, in particular, fleshing out the docs and examples.
> Wrapping middleware #1: Blueprint API and docs

- libs/pavex/Cargo.toml
Hi!
Nothing important here - just saw the headline for your talk at RustLab, looked up `pavex` on crates.io and then noticed there was no link to the repo :+1: Feel free to disregard
> Add repository link to Cargo.toml

- libs/pavex/src/blueprint/blueprint.rs
- libs/pavex/src/middleware.rs
- libs/pavex_cli/tests/ui_tests/blueprint/common/components_can_fail/lib.rs
- libs/pavex_cli/tests/ui_tests/blueprint/common/output_type_must_implement_into_response/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/common/output_type_must_implement_into_response/lib.rs
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/cannot_have_multiple_next_inputs/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/cannot_have_multiple_next_inputs/lib.rs
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/next_must_take_a_naked_generic_parameter/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/next_must_take_a_naked_generic_parameter/lib.rs
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/wrapping_middlewares_input_parameters_cannot_be_generic/expectations/stderr.txt
- libs/pavex_cli/tests/ui_tests/blueprint/wrapping_middlewares/wrapping_middlewares_input_parameters_cannot_be_generic/lib.rs
Considering the way Pavex works, this ensures that errors are raised early (by the Rust compiler against the user's code) rather than delayed (a compilation failure in the generated code).
> Lift bounds on Next's definition, rather than on its implementations

- examples/realworld/README.md
- examples/realworld/api_server_sdk/blueprint.ron
- examples/realworld/api_server_sdk/src/lib.rs
- examples/realworld/conduit_core/src/blueprint.rs
- examples/realworld/conduit_core/src/telemetry.rs
- libs/pavex/src/extract/route/matched_route.rs
- libs/pavex/src/extract/route/mod.rs
- libs/pavex/src/extract/route/raw_route_params.rs
- libs/pavexc/src/compiler/analyses/framework_items.rs
- libs/pavexc/src/compiler/app.rs
- libs/pavexc/src/compiler/codegen.rs
Now that the middleware infrastructure is in place, I can resume working on the Realworld implementation. In particular, on the logging middleware.
This PR fleshes out the primary fields, following OpenTelemetry's naming convention.  
It adds a new primitive extractor, `MatchedRouteTemplate`, in order to fulfil the requirements.
A few things are still missing though:
- Connection-level information, which is currently unavailable since we aren't propagating it down from the `Server`;
- Middlewares do not run if an incoming request fails to match one of the handlers that have been registered against the `Blueprint`. In order words, you get no logs for `404 Not Found` requests or for `405 Method Not Allowed`.
I'll try to lift both limitations in a follow-up PR.
> Realworld: logging middleware

- examples/realworld/api_server_sdk/src/lib.rs
- libs/pavexc/src/compiler/analyses/processing_pipeline/codegen.rs
- libs/pavexc/src/language/resolved_type.rs
The order of lifetimes in generated type definitions and impl blocks was not fully deterministic: we were iterating over the values of a `HashMap` in one of the intermediate steps for codegen.
This has now been replaced with a `IndexMap`, ensuring determinism.
> Deterministic lifetime ordering

- .github/workflows/docs.yml
- doc_examples/quickstart/.gitignore
- doc_examples/quickstart/05-error.snap
- doc_examples/quickstart/07-error.snap
- doc_examples/quickstart/tutorial.yml
- doc_examples/tutorial_generator/Cargo.lock
- doc_examples/tutorial_generator/Cargo.toml
- doc_examples/tutorial_generator/src/main.rs
- docs/getting_started/quickstart.md
- libs/pavex_cli/src/main.rs
I've added a `--verify` mode to `tutorial_generator`: expected error outputs are now committed to `.git` and we verify, in CI, that the auto-generated ones match what we expect.
This ensures that we never see again a regression like the one we fixed in #113: the step was failing as expected but with a completely different error from the one we wanted.
> Make sure error outputs are what we expect

- doc_examples/quickstart/05-error.snap
- doc_examples/quickstart/07-error.snap
- doc_examples/tutorial_generator/src/main.rs
- docs/Dockerfile
- docs/ansi.css
- docs/getting_started/quickstart.md
- mkdocs.yml
It took a bit of fiddling, but we now have ANSI colors in the mkdocs documentation 🖌️ 
They're not 100% faithful to what you see in the terminal, but they significantly improve readability.
> Keep ANSI colors for errors in the documentation

- libs/pavex_cli/tests/ui_tests/blueprint/router/http_method_routing_variants/expectations/app.rs
- libs/pavex_cli/tests/ui_tests/blueprint/router/http_method_routing_variants/expectations/diagnostics.dot
- libs/pavex_cli/tests/ui_tests/blueprint/router/http_method_routing_variants/lib.rs
- libs/pavexc/src/compiler/codegen.rs
Custom methods were allowed by `MethodGuard`, but they weren't tested (and they didn't work).
This PR fixes it.
> Add support for non-standard HTTP methods.

- libs/pavex_cli/src/main.rs
*Issue #, if available:* N/A
*Description of changes:* When running `pavex new demo`, invalid `Cargo.toml` files were generated for the main and server crates. This change ensures the TOML generated is valid.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> fix: broken Cargo.toml

- .gitignore
- doc_examples/tutorial_generator/Cargo.lock
- doc_examples/tutorial_generator/Cargo.toml
- doc_examples/tutorial_generator/src/main.rs
It should speed up command execution in example since we get to reuse the same target directory across patches.
> Use a separate directory for temporary files generated in doc examples

- doc_examples/guide/dependency_injection/cookbook/project/Cargo.lock
- doc_examples/guide/request_data/buffered_body/project-custom_limit.snap
- doc_examples/guide/request_data/buffered_body/project-granular_limits.snap
- doc_examples/guide/request_data/buffered_body/project/Cargo.lock
- doc_examples/guide/request_data/buffered_body/project/src/custom_limit/blueprint.rs
- doc_examples/guide/request_data/buffered_body/project/src/granular_limits/blueprint.rs
- doc_examples/guide/request_data/buffered_body/tutorial.yml
- doc_examples/guide/request_data/json/project/Cargo.lock
- doc_examples/guide/request_data/path/project/Cargo.lock
- doc_examples/guide/request_data/query/project/Cargo.lock
- doc_examples/guide/request_data/query_params/project/Cargo.lock
- doc_examples/guide/request_data/request_target/project/Cargo.lock
- doc_examples/guide/request_data/route_params/project/Cargo.lock
- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/lib.rs
- libs/pavex/src/request/body/buffered_body.rs
- libs/pavex/src/request/body/errors.rs
- libs/pavex/src/request/body/limit.rs
- libs/pavex/src/unit.rs
- libs/pavex_macros/tests/fail/serde_conflict.stderr
- libs/pavex_macros/tests/fail/serde_conflict_after_route_params_without_attributes.stderr
- libs/pavex_macros/tests/fail/serde_conflict_before_route_params_without_attributes.stderr
Manipulating bytes as `usize`s is... clunky. 
I find myself commenting on relevant lines with the value converted in the most relevant unit (e.g. MB or GB). That's a clear-cut code smell if I've ever seen one.
We introduce `ByteUnit` by re-exporting from the `ubyte` crate. It is used in [`rocket`](https://api.rocket.rs/master/rocket/data/struct.ByteUnit.html) and it fits our needs perfectly.
⚠️ Breaking change: I renamed `max_n_bytes` to `max_size` in `BodySizeLimit`. The type has also changed from `usize` to `ByteUnit`. This impacts you if you were registering a custom constructor for `BodySizeLimit`. The same applies to the `SizeLimitExceeded` error.
> Introduce ByteUnit

- docs/getting_started/index.md
- mkdocs.yml
In the docs we now link to the installers created by `cargo-dist`, which will automatically detect the user's platform and download the most appropriate CLI artifact.
All scripts and artefacts are stored alongside their respective GitHub releases, but we proxy through https://pavex.dev/ to get shorter URLs and a way to target `latest`.
> docs: Don't recommend building the CLI from source to new users

- libs/Cargo.lock
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli/src/cargo_install.rs
- libs/pavex_cli/src/pavexc/install.rs
- libs/pavex_cli/src/pavexc/location.rs
- libs/pavex_cli/src/pavexc/mod.rs
- libs/pavex_cli/src/pavexc/prebuilt.rs
Using the CLI's commit SHA as the "default" toolchain forces `pavex` to always compile `pavexc` from source when executing `pavex new` for the first time. That's not ideal.
The install module has been restructured to allow downloading from a `git` source even if we don't know its SHA. We'll switch to crates.io once Pavex is published there.
Miscellaneous improvements:
- Shell messages explaining to the user what's happening
- Fixed download URL for prebuilt `pavexc`
> Download prebuilt for "tag" toolchains

- doc_examples/guide/dependency_injection/cookbook/project/Cargo.lock
- doc_examples/guide/middleware/core_concepts/project/Cargo.lock
- doc_examples/guide/request_data/buffered_body/project/Cargo.lock
- doc_examples/guide/request_data/json/project/Cargo.lock
- doc_examples/guide/request_data/path/project/Cargo.lock
- doc_examples/guide/request_data/query/project/Cargo.lock
- doc_examples/guide/request_data/query_params/project/Cargo.lock
- doc_examples/guide/request_data/request_target/project/Cargo.lock
- doc_examples/guide/request_data/route_params/project/Cargo.lock
- libs/Cargo.lock
- libs/pavex/tests/server.rs
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli/src/confirmation.rs
- libs/pavex_cli/src/env.rs
- libs/pavex_cli/src/lib.rs
- libs/pavex_cli/src/main.rs
- libs/pavex_cli/src/pavexc/install.rs
- libs/pavex_cli/src/pavexc/mod.rs
- libs/pavex_cli/src/prebuilt.rs
- libs/pavex_cli/src/state.rs
- libs/pavex_cli/src/utils.rs
- libs/pavex_cli/src/version.rs
Another piece of the version management story: the `pavex` CLI can now install a more recent version of itself.
For completeness, we also provide an uninstall command that removes the binary as well as all the transient data that Pavex builds when compiling projects.
> Version management #2: self-updating and uninstalling

- libs/Cargo.lock
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli/src/cargo_install.rs
- libs/pavex_cli/src/cli_kind.rs
- libs/pavex_cli/src/lib.rs
- libs/pavex_cli/src/locator.rs
- libs/pavex_cli/src/main.rs
- libs/pavex_cli/src/pavexc/install.rs
- libs/pavex_cli/src/pavexc/location.rs
- libs/pavex_cli/src/prebuilt.rs
We were not considering the `.exe` extension.
> Use the correct binary filename on Windows.

- .github/workflows/docs.yml
- doc_examples/guide/dependency_injection/cookbook/project/Cargo.lock
- doc_examples/guide/middleware/core_concepts/project/Cargo.lock
- doc_examples/guide/request_data/buffered_body/project/Cargo.lock
- doc_examples/guide/request_data/json/project/Cargo.lock
- doc_examples/guide/request_data/path/project/Cargo.lock
- doc_examples/guide/request_data/query/project/Cargo.lock
- doc_examples/guide/request_data/query_params/project/Cargo.lock
- doc_examples/guide/request_data/request_target/project/Cargo.lock
- doc_examples/guide/request_data/route_params/project/Cargo.lock
- docs/getting_started/index.md
- libs/Cargo.lock
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli/src/activation.rs
- libs/pavex_cli/src/lib.rs
- libs/pavex_cli/src/main.rs
- libs/pavex_cli/src/state.rs
- libs/pavex_cli/src/user_input.rs
- libs/pavexc_cli/src/main.rs
All beta testers are currently using Pavex via `git` dependencies, either targeting a branch or a tag.  
That's... not ideal, since `cargo` doesn't really understand semver when using `git` dependencies.
To improve the experience, I want to start releasing Pavex to crates.io.  
To restrict access, this PR introduces an activation key. You'll only be prompted for this once; Pavex will remember it as you update the CLI too.
The current verification mechanism is a stop-gap solution to rush out crates.io releases. The final version will include a server with per-user keys, tied to a subscription. But since we don't want to charge closed beta testers, this is fine for now.
> Activation key

- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/blueprint/blueprint.rs
- libs/pavexc/src/compiler/generated_app.rs
This allows Pavex to play nicely with tools like `cargo watch`, avoiding spurious recompilations.
> Only persist to the disk if the content has changed

- doc_examples/quickstart/02-register_new_route.snap
- doc_examples/quickstart/02.patch
- doc_examples/quickstart/04-register_common_invocation.snap
- doc_examples/quickstart/05-bis.patch
- doc_examples/quickstart/05-error.snap
- doc_examples/quickstart/06.patch
- doc_examples/quickstart/07-error.snap
- doc_examples/quickstart/08.patch
- doc_examples/quickstart/demo-blueprint_definition.snap
- doc_examples/quickstart/demo-route_registration.snap
- doc_examples/quickstart/tutorial.yml
- docs/getting_started/quickstart/dependency_injection.md
- docs/getting_started/quickstart/routing.md
- docs/guide/dependency_injection/cookbook.md
- docs/guide/dependency_injection/core_concepts/constructors.md
- docs/guide/errors/error_handlers.md
- docs/guide/errors/error_observers.md
- docs/guide/middleware/index.md
- docs/guide/routing/request_handlers.md
- libs/pavex/src/blueprint/reflection.rs
- libs/pavexc_cli/template/app/src/blueprint.rs
- libs/pavexc_cli/template/app/src/configuration.rs
- libs/pavexc_cli/template/app/src/routes/mod.rs
Since we now support `self` and `super` paths, it doesn't make sense to call them "fully qualified path".
We retire the term in favour of **unambiguous path**.
I sneaked a little restructuring of the starter project as well (i.e. `routes::register`).
> Polish docs

- examples/starter/server/src/configuration/schema.rs
- libs/pavexc_cli/template/.env
- libs/pavexc_cli/template/server/src/configuration/schema.rs
In particular, allow setting single fields of a nested configuration struct using `split`.
> Explain how to set configuration values via env variables.

- doc_examples/quickstart/10-greet_test.snap
- doc_examples/quickstart/10.patch
- doc_examples/quickstart/tutorial.yml
It slipped through in #217 because we were only checking for a successful compilation rather than executing tests.
> Run tests for quickstart tutorial

- doc_examples/quickstart/02-new_submodule.snap
- doc_examples/quickstart/02-register_new_route.snap
- doc_examples/quickstart/02-route_def.snap
- doc_examples/quickstart/02.patch
- doc_examples/quickstart/03-route_def.snap
- doc_examples/quickstart/03.patch
- doc_examples/quickstart/04-route_def.snap
- doc_examples/quickstart/04.patch
- doc_examples/quickstart/05-bis.patch
- doc_examples/quickstart/05-error.snap
- doc_examples/quickstart/05-inject.snap
- doc_examples/quickstart/05.patch
- doc_examples/quickstart/09-greet_test.snap
- doc_examples/quickstart/09-ping_test.snap
- doc_examples/quickstart/09.patch
- doc_examples/quickstart/10-greet_test.snap
- doc_examples/quickstart/10.patch
- doc_examples/quickstart/demo-ping_handler.snap
- doc_examples/quickstart/demo-ping_test.snap
- doc_examples/quickstart/demo-route_registration.snap
- doc_examples/quickstart/tutorial.yml
- docs/getting_started/quickstart/dependency_injection.md
- docs/getting_started/quickstart/routing.md
- libs/pavexc_cli/template/app/src/routes/mod.rs
- libs/pavexc_cli/template/app/src/routes/ping.rs
- libs/pavexc_cli/template/server/Cargo.toml.liquid
- libs/pavexc_cli/template/server/tests/integration/ping.rs
Misc: update `reqwest` to `0.12`.
> Use a consistent naming scheme for request handlers.

- libs/pavex/src/blueprint/blueprint.rs
It should help `axum` users while they experiment with Pavex.
> Use `scope` as a documentation alias for `nest_at` and `nest` 

- examples/realworld/Cargo.lock
- examples/realworld/app/src/blueprint.rs
- examples/realworld/app/src/configuration.rs
- examples/realworld/server/Cargo.toml
- examples/realworld/server_sdk/Cargo.toml
- examples/realworld/server_sdk/src/lib.rs
- libs/Cargo.lock
- libs/pavex/Cargo.toml
- libs/pavex/src/cookie/components.rs
- libs/pavex/src/cookie/errors.rs
- libs/pavex/src/cookie/kit.rs
- libs/pavex/src/cookie/mod.rs
- libs/pavex/src/cookie/response.rs
- libs/pavex/src/cookie/response_cookies.rs
- libs/pavex/src/error/error_.rs
- libs/pavex/src/error/mod.rs
- libs/pavex/src/lib.rs
We re-export `biscotti` as our cookie API, with one key difference: we don't re-export `ResponseCookies` as is.
We instead expose our own `ResponseCookies` type that wraps around `biscotti`'s one, constraining its generic lifetime to be `'static` since that's what the vast majority of applications will need.
The integration is not yet ready for prime time—we need a section in the guide. But that'll come in a follow-up PR.
Other changes:
- Pavex gained a top-level `error` module, where I added an `UnexpectedError` type. Almost any application defines one as a "catch-all" error variant, therefore it looked like a win to make it first-party since we need it anyway for our own error enums.
> Cookies integration

- examples/realworld/Cargo.lock
- examples/realworld/app/src/configuration.rs
- examples/realworld/server/configuration/base.yml
- libs/Cargo.lock
We can rely on the defaults rather than specifying them explicitly.
> Update config in Realworld.

- libs/Cargo.lock
- libs/pavexc/src/compiler/analyses/call_graph/application_state.rs
There was an iteration over a `HashSet` resulting in inconsistent ordering when multiple variants are present.
> Ensure ordering of error variants for ApplicationStateError

- libs/pavex/src/kit/api.rs
The documentation stated this was already the case.
> fix: Add UrlEncodedBody to ApiKit

- libs/Cargo.lock
- libs/generate_from_path/Cargo.toml
- libs/pavex/Cargo.toml
- libs/pavex/src/telemetry/server_request_id.rs
- libs/pavex_bp_schema/Cargo.toml
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli_client/Cargo.toml
- libs/pavex_macros/Cargo.toml
- libs/pavex_miette/Cargo.toml
- libs/pavex_reflection/Cargo.toml
- libs/pavex_test_runner/Cargo.toml
- libs/pavex_tracing/Cargo.toml
- libs/pavexc/Cargo.toml
- libs/pavexc_cli/Cargo.toml
- libs/pavexc_cli_client/Cargo.toml
- libs/persist_if_changed/Cargo.toml
- libs/workspace_hack/Cargo.toml
A TypeId lets us keep all the desirable properties of a UUIDv7 (k-sortable, globally unique), with the addition of type safety (i.e. you can recognise at a glance, thanks to the prefix, if you're looking at the id for a certain resource type).
We use `sri` as prefix for the server request id.
> feat: Server request id is now represented as a TypeId

- libs/Cargo.lock
- libs/pavexc/Cargo.toml
- libs/pavexc/src/compiler/codegen.rs
- libs/pavexc/src/compiler/generated_app.rs
This ensures that paths will resolve on all platforms, Windows included.
> Use Unix path separator in Cargo.toml manifests when specifying path dependencies

- libs/pavexc_cli/template/app/Cargo.toml.liquid
- libs/pavexc_cli/template/server/Cargo.toml.liquid
Since `cargo add` will add at the bottom of the section, we move "named" sections on top.
> chore: Re-order Cargo.toml file

- libs/pavex_cli/src/command.rs
- libs/pavex_cli/src/main.rs
- libs/pavex_cli_client/src/client.rs
- libs/pavex_cli_client/src/commands/generate.rs
- libs/pavexc_cli/src/main.rs
- libs/pavexc_cli_client/src/client.rs
`--debug` was a very overloaded CLI flag: it rendered the full diagnostic error chain, exported perf profiling info and enabled internal logging.
In most cases, that's undesirable:
- Users will _often_ reach for the full diagnostic error chain
- Maintainers, instead, will look for perf profiles and internal logging
To better accommodate these usage patterns, `--debug` will now be limited to diagnostic error chains.
We introduce `--perf-profile` to emit trace files, `--log` for internal logging and an explicit `--log-filter` to configure what gets logged.
> feat: Rework CLI introspections

- libs/generate_from_path/src/template_variables/project_dir.rs
- libs/pavexc_cli/src/main.rs
It also honours the casing specified by the user, rather than converting the project directory name to kebab-case
> fix: 'pavex new' no longer panics if 'cargo fmt' fails. 

- CONTRIBUTORS.md
- libs/pavex/src/response/response_.rs
I'd like to use a Leptos trait that expects this to be available, and I couldn't think of a reason not to have it. Let me know if there are any issues
> Add status_mut() function to Response

- .gitignore
- libs/pavex/src/request/request_head.rs
Since RequestHead is non-exhaustive, to construct it I need a constructor in the defining crate.
> Add constructor for RequestHead

- libs/pavex/Cargo.toml
To aid in wasm dependency resolution for the pavex crate, I've moved the net feature for tokio behind the server flag
> Feature gate tokio net feature for pavex behind server feature

- libs/pavexc/src/compiler/analyses/call_graph/borrow_checker/move_while_borrowed.rs
The issue has been reported by @benwis: it occurs when trying to build [the Pavex-Leptos integration example](https://github.com/benwis/leptos_pavex/tree/main/examples/start_pavex).
This PR fixes the panic.
> fix: Avoid panic petgraph-related panic when inserting clone nodes to fix borrow checking errors

- CONTRIBUTORS.md
- libs/pavexc/src/rustdoc/queries.rs
While reading how Pavex works I found this todo that's low hanging. Using the fact that `self` is a reserved keyword and only appears as the first parameter in a method. 
Hope it's ok that I don't put my real name in CONTRIBUTORS.md. Love your book btw thanks!
> Handle ItemEnum kind case where function is a method

- libs/Cargo.lock
- libs/Cargo.toml
- libs/deny.toml
- libs/pavex_cli/src/command.rs
- libs/pavex_session/src/id.rs
- libs/pavex_session/src/session_.rs
- libs/pavex_session/src/store_.rs
- libs/pavex_session_memory_store/src/lib.rs
- libs/pavex_session_sqlx/Cargo.toml
- libs/pavex_session_sqlx/src/lib.rs
- libs/pavex_session_sqlx/src/postgres.rs
- libs/pavexc_cli/src/main.rs
- libs/px_workspace_hack/Cargo.toml
It's part of a more general `pavex_session_sqlx` crate, but this PR doesn't cover all the databases that `sqlx` offers.
> feat: Add a Postgres backend to pavex_session

- doc_examples/guide/middleware/pre/project-basic.snap
- doc_examples/guide/middleware/pre/project/src/core/mw.rs
- docs/guide/middleware/execution_order.md
- docs/guide/middleware/pre_processing.md
- libs/pavexc/src/compiler/analyses/processing_pipeline/codegen.rs
- libs/ui_tests/blueprint/common/components_can_fail/expectations/app.rs
- libs/ui_tests/blueprint/pre_processing_middlewares/pre_process_without_wrapping/expectations/app.rs
- libs/ui_tests/middlewares/middlewares_execution_order/diagnostics.dot
- libs/ui_tests/middlewares/middlewares_execution_order/expectations/app.rs
- libs/ui_tests/middlewares/middlewares_execution_order/expectations/diagnostics.dot
- libs/ui_tests/middlewares/middlewares_execution_order/integration/tests/run.rs
- libs/ui_tests/middlewares/middlewares_execution_order/src/lib.rs
- libs/ui_tests/middlewares/request_scoped_state_is_shared_correctly_among_middlewares/expectations/app.rs
This was an oversight.
Considering what post-processing middlewares are used for (e.g. logging response data, injecting headers, etc.) it's much more useful to have them being invoked rather than skipped when something fails on the way in.
> Execute post-processing middlewares when a pre-processing middleware returns early or fails

- CHANGELOG.md
- libs/Cargo.lock
- libs/Cargo.toml
- libs/pavex/Cargo.toml
- libs/pavex_bp_schema/Cargo.toml
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli_client/Cargo.toml
- libs/pavex_session/Cargo.toml
- libs/pavex_session_memory_store/Cargo.toml
- libs/pavex_session_sqlx/Cargo.toml
- libs/pavex_test_runner/Cargo.toml
- libs/pavex_tracing/Cargo.toml
- libs/pavexc/Cargo.toml
- libs/pavexc_cli/Cargo.toml
- libs/pavexc_cli_client/Cargo.toml
* `pavex`: 0.1.69 -> 0.1.70
* `pavex_bp_schema`: 0.1.69 -> 0.1.70
* `pavex_reflection`: 0.1.69 -> 0.1.70
* `pavex_macros`: 0.1.69 -> 0.1.70
* `persist_if_changed`: 0.1.69 -> 0.1.70
* `pavex_tracing`: 0.1.69 -> 0.1.70
* `pavex_cli`: 0.1.69 -> 0.1.70
* `pavex_cli_deps`: 0.1.69 -> 0.1.70
* `pavex_miette`: 0.1.69 -> 0.1.70
* `pavexc_cli_client`: 0.1.69 -> 0.1.70
* `pavexc`: 0.1.69 -> 0.1.70
* `pavexc_rustdoc_types`: 0.1.69 -> 0.1.70
* `pavex_cli_client`: 0.1.69 -> 0.1.70
* `pavex_session`: 0.1.69 -> 0.1.70
* `pavex_session_memory_store`: 0.1.69 -> 0.1.70
* `pavex_session_sqlx`: 0.1.69 -> 0.1.70
* `pavexc_cli`: 0.1.69 -> 0.1.70
* `generate_from_path`: 0.1.69 -> 0.1.70
<details><summary><i><b>Changelog</b></i></summary><p>
</p></details>
---
This PR was generated with …
> chore: release v0.1.70

- CHANGELOG.md
- libs/Cargo.lock
- libs/Cargo.toml
- libs/pavex/Cargo.toml
- libs/pavex_bp_schema/Cargo.toml
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli_client/Cargo.toml
- libs/pavex_cli_deps/Cargo.toml
- libs/pavex_cli_flock/Cargo.toml
- libs/pavex_session/Cargo.toml
- libs/pavex_session_memory_store/Cargo.toml
- libs/pavex_session_sqlx/Cargo.toml
- libs/pavex_test_runner/Cargo.toml
- libs/pavex_tracing/Cargo.toml
- libs/pavexc/Cargo.toml
- libs/pavexc_cli/Cargo.toml
- libs/pavexc_cli_client/Cargo.toml
* `pavex`: 0.1.70 -> 0.1.71
* `pavex_bp_schema`: 0.1.70 -> 0.1.71
* `pavex_reflection`: 0.1.70 -> 0.1.71
* `pavex_macros`: 0.1.70 -> 0.1.71
* `persist_if_changed`: 0.1.70 -> 0.1.71
* `pavex_tracing`: 0.1.70 -> 0.1.71
* `pavex_cli`: 0.1.70 -> 0.1.71
* `pavex_cli_deps`: 0.1.70 -> 0.1.71
* `pavex_cli_shell`: 0.1.70 -> 0.1.71
* `pavex_cli_flock`: 0.1.70 -> 0.1.71
* `pavex_miette`: 0.1.70 -> 0.1.71
* `pavexc_cli_client`: 0.1.70 -> 0.1.71
* `pavexc`: 0.1.70 -> 0.1.71
* `pavexc_rustdoc_types`: 0.1.70 -> 0.1.71
* `pavex_cli_client`: 0.1.70 -> 0.1.71
* `pavex_session`: 0.1.70 -> 0.1.71
* `pavex_session_memory_store`: 0.1.70 -> 0.1.71
* `pavex_session_sqlx`: 0.1.70 -> 0.1.71
* `pavexc_cli`: 0.1.70 -> 0.1.71
* `generate_from_path`: 0.1.70 -> 0.1.71 …
> chore: release v0.1.71

- doc_examples/tutorial_generator/src/main.rs
- libs/pavex_cli/src/main.rs
- libs/pavex_miette/src/graphical_report_handler.rs
- libs/pavex_test_runner/src/snapshot.rs
- **feat: Nudge users towards PAVEX_DEBUG if they need to investigate errors further**
- **feat: When printing an error chain, deduplicate identical errors to reduce visual noise**
> Surface our debugging story

- dist-workspace.toml
- libs/Cargo.lock
- libs/Cargo.toml
- libs/pavex_cli/Cargo.toml
- libs/pavex_cli/src/prebuilt.rs
- libs/pavex_cli/tests/dependency_tree.rs
- libs/px_workspace_hack/Cargo.toml
Use Rust-native decompression crates to avoid install issues related to missing system dependencies on the user's host.
> feat: Don't require native libraries to decompress archives from GitHub.

- libs/pavexc/src/language/resolved_path.rs
Fixes a (rare) panic in project generation.
See [this run](https://github.com/LukeMathWalker/pavex/actions/runs/13474322246/job/37651593168) as an example of the failure.
> fix: Compare path length before iterating in lock step over their segments.

- .github/workflows/docs.yml
- ci_utils/templates/job_steps/tests.jinja
- libs/pavex_session/src/store_.rs
- libs/pavex_session/tests/session/fixtures.rs
- libs/pavex_session_memory_store/src/lib.rs
- libs/pavex_session_sqlx/src/postgres.rs
We gain very little by allowing methods to be non-`Send` futures when the store itself is already required to be `Send` and `Sync`.
> Enforce `Send`-ness for `SessionStore` methods

- examples/starter/Dockerfile
- libs/pavex_cli/src/pavexc/mod.rs
- libs/pavexc_cli/template/Dockerfile
The check used to be run on installation, but this causes issues with CI caching: if the binary is restored from a cache in a new runner, the environment hasn't gone through the setup but the flow won't trigger since the binary is already where we expect it to be.
We now run the setup flow unconditionally.
Fixes #474
> fix: Always check if pavexc dependencies are installed

- .github/workflows/docs.yml
- CONTRIBUTORS.md
- docs/tools/tutorial_generator/Cargo.lock
- libs/Cargo.lock
- libs/Cargo.toml
- libs/pavex_session_redis/.github/services.yml
- libs/pavex_session_redis/CONTRIBUTING.md
- libs/pavex_session_redis/Cargo.toml
- libs/pavex_session_redis/docker-compose.yml
- libs/pavex_session_redis/src/lib.rs
- libs/pavex_session_redis/tests/tests.rs
> Redis session store
